version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-api
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=felipe
      - POSTGRES_PASSWORD=felipe_123
      - POSTGRES_DB=users
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: user-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: felipe
      POSTGRES_PASSWORD: felipe_123
      POSTGRES_DB: users
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
